### ISSUE TITLE
[SOLVED] Kernel won't boot

### ISSUE THREAD

**Issue by SharkEzz** [ananjaser1211/Refinedkernel_2#2]
Hello

I'm currently trying to compile Refined Kernel (from commit 
849b6d385ffba3868e613513bd834566c4b5f2a0 of the master branch) but can not get it to boot.
When the kernel is compiled (boot_J530F_G.img), I transfer it (the .img file) to my J5 and I flash it using TWRP. I just flash the img.
Only when I restart, the J5 logo is displayed then I have a black screen during a few seconds then my phone reboot, the J5 logo reappears and it boot directly into TWRP.
I'm using UBERTC 4.9 as a toolchain and compile under Ubuntu 16.04.3 LTS (updated) and my J5 is a J530F, I'm using the script "build_j530f.sh" and the paths inside the scripts are well defined and the script is launched with the "sudo" command.
Below, some screenshots of the few messages displayed during compilation.

Also, I had to create the folder "out" in rf-tools because otherwise I had an error that the folder did not exist and the script did not copy the .img file.

![capture du 2018-02-18 16-38-17](https://user-images.githubusercontent.com/27637158/36353864-2740fbc2-14cc-11e8-9dd6-5931edda778b.png)
![capture du 2018-02-18 16-38-43](https://user-images.githubusercontent.com/27637158/36353865-275cdf9a-14cc-11e8-9f24-1989aa236154.png)
![capture du 2018-02-18 16-40-56](https://user-images.githubusercontent.com/27637158/36353866-2778e442-14cc-11e8-9ea3-631d4c952094.png)
![capture du 2018-02-18 16-41-14](https://user-images.githubusercontent.com/27637158/36353867-2795c742-14cc-11e8-9bce-a8c2c97145d8.png)
![capture du 2018-02-18 16-42-31](https://user-images.githubusercontent.com/27637158/36353868-27b1e008-14cc-11e8-9510-c1cbb5710803.png)

Any help would be great !

**Comment by ananjaser1211** [comment]
Hello, first please switch to cronos.sh build script as the old ones had many issue that requires sudo to pack ramdisk/zimage. Just define your Toolchain at the top. Second I had similar problem first time I synced the source which was later pinned down to be a ramdisk error. Due to how ramdisks contain bunch of empty directories. Git won't synced them. A workaround was attempted at https://github.com/ananjaser1211/Refinedkernel_2/commit/bab7b7992bde8a161461ca483db87633b93c46af
To force commit. Would be great if you can check for those committed folder in your rf-tools/unified/ramdisk
You can manually create them or just Meld stock ramdisk with mine and add missing folders (assuming place holder method didn't sync them)
But again id suggest the new script as it deals with packing much better.

Best regards.

**Comment by SharkEzz** [comment]
I did what you told me, I added the missing files by hand and everything works perfectly!

Thank you very much for your help !

After a few minutes of testing, nothing to report except that the control of the GPU is not displayed in the settings of the kernel (I use Kernel Adiutor). For the CPU everything is fine the basic frequency is well to 1.7 Ghz !

Regards

**Comment by ananjaser1211** [comment]
Awesome, glad it worked out. regarding GPU frequency you need to either manually edit it in sys-path or use EX Kernel manager, base clock is set higher than normal so shouldnt be a big bump even after pushing it more inside kernel manager. that should do it until i add synapse integration.
